[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/login.html"
  to = "/admin/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/admin/login.html"
  status = 301
  force = true

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200